# Generated by Django 5.2 on 2025-04-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('population', models.PositiveIntegerField()),
                ('capital', models.CharField(max_length=100)),
                ('flag', models.URLField()),
            ],
        ),
    ]
