
name: Fullstack CI/CD Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ### === BACKEND (Django) === ###
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./main/main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
        working-directory: ./main/main

      - name: Run backend tests
        run: python manage.py test
        working-directory: ./main

      - name: Collect static files
        run: python manage.py collectstatic --noinput
        working-directory: ./main


  ### === FRONTEND (React) === ###
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flagfrontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
         node-version: '14' 

      - name: Install dependencies (frontend)
        run: |
            cd flagfrontend  # Change directory to the frontend folder
            npm install  # Install the frontend dependencies
          
      - name: Install dependencies
        working-directory: ./flagfrontend
        run: npm install
       
      - name: Run Frontend Tests
        working-directory: ./flagfrontend
        run: npm test -- --watchAll=false


      - name: Run React Tests
        run: npm test -- --watchAll=false

      - name: Build React App
        run: npm run build

  ### === PACKAGE BOTH === ###
  package:
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Package Folder
        run: |
          mkdir dist
          cp -r flagfrontend/build dist/frontend
          cp -r flagbackend dist/backend
          echo "Packaging complete."

      - name: Upload Deployment Artifact
        uses: actions/upload-artifact@v3
        with:
          name: fullstack-app
          path: dist
